// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDvePQVFKWZQwcyvXHrMPu7VYTS4sJMu78',
    appId: '1:1049017393316:web:2c418b79eaf761db36c631',
    messagingSenderId: '1049017393316',
    projectId: 'vehiclematch-7b84e',
    authDomain: 'vehiclematch-7b84e.firebaseapp.com',
    storageBucket: 'vehiclematch-7b84e.appspot.com',
    measurementId: 'G-8V2GDPH03C',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAEIh8Yes6skUQQtr1p5kqAQttaJE-AbQY',
    appId: '1:1049017393316:android:feaa1ff60632a6b136c631',
    messagingSenderId: '1049017393316',
    projectId: 'vehiclematch-7b84e',
    storageBucket: 'vehiclematch-7b84e.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDtejTsVlv-oU3HpVFa-dJX9xmH-ycrrmM',
    appId: '1:1049017393316:ios:6318e8c0e6b4748f36c631',
    messagingSenderId: '1049017393316',
    projectId: 'vehiclematch-7b84e',
    storageBucket: 'vehiclematch-7b84e.appspot.com',
    iosClientId: '1049017393316-mv9j7s1nngvhlipb54sn9p8bmblfl8m4.apps.googleusercontent.com',
    iosBundleId: 'com.example.vehicleMatch',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDtejTsVlv-oU3HpVFa-dJX9xmH-ycrrmM',
    appId: '1:1049017393316:ios:6318e8c0e6b4748f36c631',
    messagingSenderId: '1049017393316',
    projectId: 'vehiclematch-7b84e',
    storageBucket: 'vehiclematch-7b84e.appspot.com',
    iosClientId: '1049017393316-mv9j7s1nngvhlipb54sn9p8bmblfl8m4.apps.googleusercontent.com',
    iosBundleId: 'com.example.vehicleMatch',
  );
}
